### ISSUE TITLE
javascript error

### ISSUE THREAD

**Issue by chocorexic** [brianblakely/nodep-date-input-polyfill#17]
Since the update to 4.0.1 I've been getting this error in the console:

`TypeError: b.data(c).split is not a function. (In 'b.data(c).split(" ")', 'b.data(c).split' is undefined)`

Happening in firefox 48.0 on mint and safari 9.1.2. Will check to make sure it's not the build process causing problems with the javascript, just wanted to check if others have come across a similar issue? The error causes the selected date to not display in the input element, but the correct value and format (yyyy-MM-dd) is being selected.

**Comment by brianblakely** [comment]
`.data` is not in the referenced anywhere in the distributable, so I suspect is this error is in the app code.

That said, if said error is caused indirectly by the library doing something unintuitive, please call it out.

Will tentatively close as invalid, but will reopen pending an update from you.  Thanks for the report!

**Comment by chocorexic** [comment]
That's cool, I'll update if I can find out any more. I forgot to mention that I'm trying to use this via an angular 2 form. The previous version was almost fully working but had issue #16. The two-way data-binding still works so I can log the selected dates in the console.

**Comment by brianblakely** [comment]
The value property of the element now has a custom getter/setter. I wouldn't be surprised if that was throwing Angular off its game. 

Unfortunately I think this is necessary to separate the displayed date from the underlying value.
